version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    container_name: frontend
    hostname: frontend
    ports:
      - 3000:3000

  backend:
    env_file: .env
    depends_on:
      - mongo
    build:
      context: ./backend
    container_name: backend
    hostname: backend
    ports:
      - 8080:8080

  mongo:
    env_file: .env
    image: mongo:latest
    container_name: mongodb
    hostname: db
    ports:
      - 27017:27017
